#!/usr/bin/env bash
bash -n "$0" | exit 1

DBNAME=$1
TESTNAME="verify_index_expressions"
SQL="$TESTNAME.sql"
OUTPUT="$TESTNAME.out"
EXPECTED="$TESTNAME.expected"

rm -f $OUTPUT

cdb2sql ${CDB2_OPTIONS} -f $SQL $DBNAME default > $OUTPUT
cdb2sql ${CDB2_OPTIONS} $DBNAME default "explain select * from names where id < 2" >> $OUTPUT
cdb2sql ${CDB2_OPTIONS} $DBNAME default "exec procedure sys.cmd.verify('names')" >> $OUTPUT
diff $OUTPUT $EXPECTED > /dev/null
rc=$?
if [[ $rc -ne 0 ]]; then
    echo "Failed $TESTNAME test"
    echo diff $(pwd)/$OUTPUT $(pwd)/$EXPECTED
fi

exit $rc
